### ISSUE TITLE
应用纯白配色窗口大小好像不能更改了？

### ISSUE THREAD

**Issue by Cescfangs** [hi-caicai/Farbox-Editor-#1]
FarBox 默认的配色方案下窗口大小是可以正常更改的，不知道这个是不是 bug？
感觉看起来更像是 Farbox 的锅，毕竟 CSS 只是更改配色方案？

**Comment by hi-caicai** [comment]
窗口可以更改大小的，这好像不是bug～，本身app 就支持

**Comment by Cescfangs** [comment]
首先，非常感谢 caicai 这么及时的回复！

请相信我绝对不是那种连窗口能不能调整大小都不知道的人【捂脸。
默认的`CSS`文件下，当鼠标指针放到边界时，会变成上下伸缩的那种，所有的 app 都那样，FarBox 也不例外，另外在 Mac 下，双击窗口会调整到适宜的大小，这在默认的`CSS`也是支持的，但是换成 caicai 的`CSS`之后这两样都不行了。

我觉得自己还是太草率了，这不算是一个很复杂问题，我自己应该先看看问题出在哪里，不应该急着来问，然后我对比了一下默认的`CSS`代码和 caicai 提供的`CSS`（黑白都一样），发现 caicai 的多了以下五行：

``` css
tb_bg_bottom_line_color: #202020
tb_bg_color1: #303030
tb_bg_color2: #2B2B2B
tb_bg_color3: #222222
tb_font_color: #999999
```

很直观的感觉是把多出来的五项删了试试，嗯，问题解决了，所以我在想是不是 FarBox 的`CSS`文件或者说界面布置在不同平台下是稍微有所区别的？

最后，非常感谢 caicai 提供的 `CSS` 配色以及 FarBox 模板，我现在用的正是你的模板！

**Comment by hi-caicai** [comment]
嗷嗷，检查了下，“双击窗口会调整到适宜的大小”，这个问题存在的
btw ，那几行好像是开发者特别提供给我的，因为我说顶部的颜色能不能换掉～，哈哈哈（有啥问题欢迎给我留言）

这个问题会在开发者新的编辑器里解决，马上要发布了～，可以关注下farbox
